const SPREADSHEET_ID='1YWmUfGar1EYewF7m4kXt8ymKCekTkGjteJxUnJYI4bE';
const TZ='Asia/Muscat';
const SH={teachers:'المعلمون',records:'سجل الاحتياط',timetable:'الجدول الأسبوعي',rules:'قواعد التوزيع',cycles:'دورات الاحتياط',settings:'إعدادات النظام'};
function out(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function ss(){return SpreadsheetApp.openById(SPREADSHEET_ID)}
function sheet(n){const s=ss().getSheetByName(n);if(!s)throw Error('الورقة غير موجودة: '+n);return s}
function doGet(e){try{const a=(e.parameter.action||'bootstrap');if(a==='ping')return out({ok:true});if(a==='now')return out({ok:true,...serverNow()});if(a==='teachers')return out({ok:true,teachers:getTeachers()});if(a==='timetable')return out({ok:true,timetable:getTimetable()});if(a==='records')return out({ok:true,records:getRecords()});if(a==='bootstrap')return out({ok:true,teachers:getTeachers(),timetable:getTimetable(),records:getRecords(),cycles:getCycles(),serverNow:serverNow()});return out({ok:false,error:'إجراء غير معروف'})}catch(x){return out({ok:false,error:x.message})}}
function doPost(e){const lock=LockService.getScriptLock();lock.waitLock(20000);try{const d=JSON.parse(e.postData.contents||'{}');let r;if(d.action==='saveDay')r=saveDay(d);else if(d.action==='updateTeacher')r=updateTeacher(d);else if(d.action==='startCycle')r=startCycle(d);else throw Error('إجراء غير معروف');SpreadsheetApp.flush();return out({ok:true,...r})}catch(x){return out({ok:false,error:x.message})}finally{lock.releaseLock()}}
function serverNow(){const n=new Date(),date=Utilities.formatDate(n,TZ,'yyyy-MM-dd'),dow=+Utilities.formatDate(n,TZ,'u');const days={1:'الإثنين',2:'الثلاثاء',3:'الأربعاء',4:'الخميس',5:'الجمعة',6:'السبت',7:'الأحد'};return{date,day:days[dow],time:Utilities.formatDate(n,TZ,'HH:mm:ss'),timezone:TZ}}
function getTeachers(){const v=sheet(SH.teachers).getDataRange().getValues();return v.slice(1).filter(r=>r[0]).map(r=>({name:String(r[0]),base:+r[1]||0,reserveCount:+r[2]||0,currentLoad:+r[3]||(+r[1]||0),remaining:+r[4]||0,lastReserve:fmt(r[5]),status:String(r[6]||''),eligible:String(r[7]||'نعم')!=='لا',scheduleName:String(r[8]||r[0])}))}
function getTimetable(){const v=sheet(SH.timetable).getDataRange().getValues();return v.slice(1).filter(r=>r[0]&&r[1]).map(r=>({teacher:String(r[0]),day:String(r[1]),periods:Object.fromEntries([1,2,3,4,5,6,7,8].map((p,i)=>[p,String(r[i+2]||'')])),dailyCount:+r[10]||0}))}
function fmt(v){return v instanceof Date?Utilities.formatDate(v,TZ,'yyyy-MM-dd'):String(v||'')}
function getRecords(){const v=sheet(SH.records).getDataRange().getValues();return v.slice(1).filter(r=>r[0]).map(r=>({id:String(r[0]),date:fmt(r[1]),day:String(r[2]),absent:String(r[3]),period:+r[4],reserve:String(r[5]||''),className:String(r[6]||''),approvedAt:fmt(r[7]),notes:String(r[8]||'')}))}
function getCycles(){const s=ss().getSheetByName(SH.cycles);if(!s)return[];const v=s.getDataRange().getValues();return v.slice(1).filter(r=>r[0]).map(r=>({number:+r[0],start:fmt(r[1]),end:fmt(r[2]),target:+r[3]||0,done:+r[4]||0,progress:r[5],completed:+r[6]||0,status:String(r[7]||''),notes:String(r[8]||'')}))}
function updateTeacher(d){if(!d.name)throw Error('اسم المعلم مطلوب');const s=sheet(SH.teachers),v=s.getDataRange().getValues();let row=v.findIndex((r,i)=>i>0&&String(r[0])===String(d.name));if(row<0){if(!d.create)throw Error('المعلم غير موجود');row=s.getLastRow();s.getRange(row+1,1,1,9).setValues([[d.name,+d.base||0,0,+d.base||0,Math.max(0,25-(+d.base||0)),'','متاح',d.eligible===false?'لا':'نعم',d.scheduleName||d.name]])}else{s.getRange(row+1,2).setValue(+d.base||0);s.getRange(row+1,8).setValue(d.eligible===false?'لا':'نعم');if(d.scheduleName)s.getRange(row+1,9).setValue(d.scheduleName)}return{teachers:getTeachers()}}
function hardValidate(r,teachers,tt,dayRows,batchNames,absentNames){const t=teachers.find(x=>x.name===r.reserve);if(!t||!t.eligible)throw Error('معلم الاحتياط غير مؤهل: '+r.reserve);if(absentNames.has(r.reserve))throw Error('لا يمكن تكليف معلم مسجل غائبًا في هذا اليوم: '+r.reserve);const row=tt.find(x=>x.teacher===r.reserve&&x.day===r.day);if(!row)throw Error('لا يوجد جدول معتمد لـ '+r.reserve);if(row.periods[r.period])throw Error(r.reserve+' لديه حصة أصلية في الحصة '+r.period);if(batchNames.has(r.reserve))throw Error('لا يجوز إسناد أكثر من احتياط للمعلم نفسه في اليوم');batchNames.add(r.reserve);const oldSame=dayRows.filter(x=>x.reserve===r.reserve).length;const hist=t.reserveCount-oldSame;if(t.base+hist+1>25)throw Error(r.reserve+' أكمل نصاب الدورة')}
function saveDay(d){if(!d.date||!d.day)throw Error('التاريخ واليوم مطلوبان');const incoming=(d.records||[]).map(r=>({...r,date:d.date,day:d.day,period:+r.period}));const assigned=incoming.filter(r=>r.reserve);const all=getRecords(),same=all.filter(r=>r.date===d.date&&r.day===d.day),teachers=getTeachers(),tt=getTimetable(),seen=new Set(),absentNames=new Set(incoming.map(r=>String(r.absent||'')).filter(Boolean));assigned.forEach(r=>hardValidate(r,teachers,tt,same,seen,absentNames));const s=sheet(SH.records),v=s.getDataRange().getValues();for(let i=v.length-1;i>=1;i--)if(fmt(v[i][1])===d.date&&String(v[i][2])===d.day)s.deleteRow(i+1);if(incoming.length)s.getRange(s.getLastRow()+1,1,incoming.length,9).setValues(incoming.map(r=>[r.id||Utilities.getUuid(),new Date(r.date+'T12:00:00'),r.day,r.absent,r.period,r.reserve||'',r.className||'',new Date(),r.reserve?(r.exceptional?'استثنائي':''):'غير مسند - لا يوجد متاح']));return{records:getRecords(),teachers:getTeachers()}}
function startCycle(d){const s=sheet(SH.cycles),cycles=getCycles(),active=cycles.find(x=>x.status==='نشطة');if(active){const row=cycles.findIndex(x=>x.number===active.number)+2;s.getRange(row,3).setValue(new Date());s.getRange(row,8).setValue('مغلقة')}const n=cycles.length?Math.max(...cycles.map(x=>x.number))+1:1;const target=getTeachers().filter(x=>x.eligible).reduce((a,t)=>a+Math.max(0,25-t.base),0);s.appendRow([n,new Date(),' ',target,0,'0%',0,'نشطة',d.notes||'']);return{cycles:getCycles()}}
